---
abstract: Foo
author:
  - 'Michal Wojciechowski <odyniec@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  File::Spec::Functions: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Foo-Bar
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Foo::Bar:
    file: lib/Foo/Bar.pm
    version: 0.010
requires:
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/odyniec/p5-Foo-Bar/issues
  homepage: https://github.com/odyniec/p5-Foo-Bar
  repository: https://github.com/odyniec/p5-Foo-Bar.git
version: 0.010
